name: Build and Push Docker Image

on:
  push:
    branches:
      - release  # Se ejecuta cuando se hace un push o merge a la rama release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17  # Asegúrate de usar la versión de JDK que necesitas
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # Cambia a la versión de Java que estés usando

    - name: Build Maven project
      run: mvn clean package -DskipTests  # Compila tu proyecto sin ejecutar los tests

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build -t kunder9/cxn-app:latest .

    - name: Push Docker image
      run: docker push kunder9/cxn-app:latest
